module C = Configurator.V1

let has_prefix str prefix =
  let lp = String.length prefix in
  let ls = String.length str in
  ls >= lp && String.sub str 0 lp = prefix

let add_unique_flag existing flag =
  if List.mem flag existing then existing else existing @ [ flag ]

let has_lib path =
  let lib = Filename.concat path "lib" in
  let checks =
    [ "libicuuc.a"; "libicuuc.so"; "libicuuc.dylib"; "libicuuc.78.2.dylib"
    ; "libicui18n.a"; "libicui18n.so"; "libicui18n.dylib"; "libicui18n.78.2.dylib" ] in
  List.exists (fun name -> Sys.file_exists (Filename.concat lib name)) checks

let has_headers path =
  Sys.file_exists (Filename.concat path "include/unicode/utypes.h")

let normalize_prefix_from_cflags cflags =
  let includes = List.filter (fun flag -> has_prefix flag "-I") cflags in
  match includes with
  | flag :: _ when String.length flag > 2 ->
    (try
       let include_path = String.sub flag 2 (String.length flag - 2) in
       Some (Filename.dirname include_path)
     with _ -> None)
  | _ -> None

let add_missing_icu_uc libs = add_unique_flag libs "-licuuc"

let has_library_path libs =
  List.exists (fun flag -> has_prefix flag "-L") libs

let add_lib_dir_if_missing maybe_prefix libs =
  match maybe_prefix with
  | None -> libs
  | Some prefix ->
    if has_library_path libs then
      libs
    else
      let path = "-L" ^ Filename.concat prefix "lib" in
      path :: libs

let split_tokens line =
  String.split_on_char ' ' line
  |> List.filter (fun s -> String.length s > 0)

let parse_define_value lines key =
  let rec loop = function
    | [] -> None
    | line :: rest ->
      (match split_tokens line with
       | "#define" :: name :: value :: _ when name = key -> Some value
       | _ -> loop rest)
  in
  loop lines

let parse_icu_version_suffix header_path =
  if not (Sys.file_exists header_path) then
    None
  else
    let lines =
      let ch = open_in header_path in
      let rec read acc =
        try
          read (input_line ch :: acc)
        with End_of_file ->
          close_in ch;
          List.rev acc
      in
      read [] in
    match parse_define_value lines "U_ICU_VERSION_SUFFIX" with
    | Some value -> Some value
    | None ->
      (match parse_define_value lines "U_ICU_VERSION_MAJOR_NUM" with
       | Some major when String.length major > 0 -> Some ("_" ^ major)
       | _ -> None)

let infer_version_suffix_from_prefix prefix =
  parse_icu_version_suffix (Filename.concat prefix "include/unicode/uvernum.h")

let write_config_file version_suffix =
  let oc = open_out "icu4c_config.ml" in
  output_string oc "(* Auto-generated by discover. Do not edit manually. *)\n";
  output_string oc "let version_suffix = \"";
  output_string oc version_suffix;
  output_string oc "\"\n";
  close_out oc

let normalize_flags prefix flags =
  let cflags = flags.C.Pkg_config.cflags in
  let libs =
    flags.C.Pkg_config.libs
    |> add_lib_dir_if_missing prefix
    |> add_missing_icu_uc in
  C.Pkg_config.({ cflags; libs })

let find_prefix_by_fallback () =
  let candidates =
    [ "/opt/homebrew/Cellar/icu4c@78/78.2"
    ; "/opt/homebrew/opt/icu4c@78/78.2"
    ; "/opt/homebrew/opt/icu4c"
    ; "/usr/local/Cellar/icu4c@78/78.2"
    ; "/usr/local/opt/icu4c"
    ; "/usr" ] in
  let prefix_candidates =
    match Sys.getenv_opt "ICU_PREFIX" with
    | Some custom -> custom :: candidates
    | None -> candidates in
  List.find_opt (fun prefix -> has_headers prefix && has_lib prefix) prefix_candidates

let try_pkg_config c =
  let config_paths =
    [ "/opt/homebrew/Cellar/icu4c@78/78.2/lib/pkgconfig"
    ; "/opt/homebrew/opt/icu4c/lib/pkgconfig"
    ; "/usr/local/opt/icu4c/lib/pkgconfig" ] in
  let current =
    Option.value (Sys.getenv_opt "PKG_CONFIG_PATH") ~default:"" in
  Unix.putenv "PKG_CONFIG_PATH"
    (String.concat ":" (current :: List.filter Sys.file_exists config_paths));
  match C.Pkg_config.get c with
  | None -> None
  | Some pc ->
    (match C.Pkg_config.query pc ~package:"icu-i18n" with
     | None -> None
     | Some deps ->
       let prefix = normalize_prefix_from_cflags deps.C.Pkg_config.cflags in
       Some (prefix, normalize_flags prefix deps))

let () =
  C.main ~name:"icu" (fun c ->
    let prefix, flags =
      match try_pkg_config c with
      | Some (prefix, deps) -> (prefix, deps)
      | None ->
        (match find_prefix_by_fallback () with
         | Some prefix ->
           let lib_dir = Filename.concat prefix "lib" in
           let normalized =
             C.Pkg_config.({
               cflags = ["-I" ^ Filename.concat prefix "include"];
               libs = ["-L" ^ lib_dir; "-licui18n"];
             }) in
           (Some prefix, normalize_flags (Some prefix) normalized)
         | None ->
           failwith "Unable to locate ICU headers and libraries; install ICU (icu4c) or set PKG_CONFIG_PATH") in
    let version_suffix =
      match prefix with
      | Some icu_prefix ->
        infer_version_suffix_from_prefix icu_prefix
        |> Option.value ~default:"_78"
      | None ->
        "_78" in
    write_config_file version_suffix;
    C.Flags.write_sexp "c_flags.sexp" flags.cflags;
    C.Flags.write_sexp "c_libs.sexp" flags.libs)
