hoist: true

ignoredBuiltDependencies:
  - '@scarf/scarf'
  - esbuild
  - rescript
  - rescript-embed-lang

onlyBuiltDependencies:
  - '@rolandpeelen/rewatch'
  - bun
  - rescript-embed-lang

overrides:
  common: link:packages/shared-types

workspaces:
  - packages/*
  - packages/*/*
  - demos/*
  - demos/*/*
